src/Entity/Building.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Building
 *
 * @ORM\Table(name="building", indexes={@ORM\Index(name="architect_id", columns={"architect_id"})})
 * @ORM\Entity
 */
class Building
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=100, nullable=false)
     */
    private $name;

    /**
     * @var string|null
     *
     * @ORM\Column(name="place", type="string", length=100, nullable=true)
     */
    private $place;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="completion_date", type="date", nullable=true)
     */
    private $completionDate;

    /**
     * @var int|null
     *
     * @ORM\Column(name="height_meters", type="integer", nullable=true)
     */
    private $heightMeters;

    /**
     * @var \Architect
     *
     * @ORM\ManyToOne(targetEntity="Architect")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="architect_id", referencedColumnName="id")
     * })
     */
    private $architect;

    public function getName()
    {
        return $this->name;
    }

    public function getPlace()
    {
        return $this->place;
    }

    public function getArchitect()
    {
        return $this->architect;
    }

    public function getArchitectName()
    {
        return $this->architect->getName();
    }
}

src/Controller/BuildingController.php
<?php

namespace App\Controller;

use App\Entity\Building;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;

class BuildingController extends AbstractController
{
    /**
     * @Route("/building", name="app_building")
     */
    public function list(EntityManagerInterface $entityManager)
    {
        $buildings = $entityManager
            ->getRepository(Building::class)
            ->findAll();

        return $this->render('building/list.html.twig', [
            'buildings' => $buildings,
        ]);
    }
}

templates/building/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Buildings{% endblock %}

{% block body %}

    <header><h1>Buildings</h1></header>

    <aside>
       Search : <input type="text" placeholder="name" class="form-control mb-4" id="searcher">
    </aside>

    <section id="list">
        {% for building in buildings %}
            <div>
            {{ building.name }} : {{ building.place }} ::
            <a href="/architect/{{ building.architect }}">{{ building.architectName }}</a>
            </div>
        {% else %}
            <div class="text-info">No records found ❌</div>
        {% endfor %}
    </section>

{% endblock %}